<<<<<<< HEAD
# Generated by Django 3.2 on 2021-06-11 13:39
=======
# Generated by Django 3.2 on 2021-06-12 08:36
>>>>>>> eabfc3d1699f7e5b430d8a420d27b390a9af554d

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20210509_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
